const images = {
    addPicture: require('./images/addpicture.png'),
    arrive: require('./images/arrive.png'),
    board: require('./images/board.png'),
    cancel: require('./images/cancel.png'),
    clockGreen: require('./images/clock_green.png'),
    clockYellow: require('./images/clock_yellow.png'),
    customService: require('./images/custom_service.png'),
    delete: require('./images/delete.png'),
    drownArrow: require('./images/down_arrow.png'),
    driver: require('./images/driver.png'),
    edit: require('./images/edit.png'),
    envelope: require('./images/envelope.png'),
    headImage: require('./images/head_image.png'),
    head: require('./images/head.png'),
    homeBlack: require('./images/home_black.png'),
    homeGray: require('./images/home_gray.png'),
    homeGreen: require('./images/home_green.png'),
    icLauncherRound: require('./images/ic_launcher_round.png'),
    icLauncher: require('./images/ic_launcher.png'),
    leftSlidbar: require('./images/left_slidebar.png'),
    left: require('./images/left.png'),
    locationJian: require('./images/location_jian.png'),
    location: require('./images/location.png'),
    loginLogo: require('./images/login_logo.png'),
    logo: require('./images/logo.png'),
    mapHome: require('./images/map_home.png'),
    navi: require('./images/navi.png'),
    peopleSitdown: require('./images/people_sitdown.png'),
    people: require('./images/people.png'),
    phone: require('./images/phone.png'),
    pingxing: require('./images/pingxing.png'),
    qrcode: require('./images/qrcode.png'),
    question: require('./images/question.png'),
    rightArrowWhite: require('./images/right_arrow_white.png'),
    rightArrow: require('./images/right_arrow.png'),
    rightImage: require('./images/right_image.png'),
    scanWhite: require('./images/scan_white.png'),
    scan: require('./images/scan.png'),
    selectedPinxing: require('./images/selected_pinxing.png'),
    successGreen: require('./images/success_green.png'),
    time: require('./images/time.png'),
    topImage: require('./images/top_image.png'),
    upArrow: require('./images/up_arrow.png'),
    workBlack: require('./images/work_black.png'),
    workGray: require('./images/work_gray.png'),
    workGreen: require('./images/work_green.png'),
    yes: require('./images/yes.png'),


}

export default images
