const images = {
    bgImage: require('./images/bg_dl.png'),
    homeBgImage: require('./images/bg_top1.png'),
    bgDown: require('./images/bg_jy_dnow.png'),
    bgCalendar: require('./images/bg_jy.png'),
    phone: require('./images/phone.png'),
    peopleGroup: require('./images/ic_rs.png'),
    address: require('./images/ic_dw.png'),
    clock: require('./images/ic_time.png'),
    yes: require('./images/ic_gou.png'),
    no: require('./images/ic_cha.png'),
    avatar1: require('./images/pic_ls_tx.png'),
    avatar2: require('./images/pic_my_tx.png'),
    avatar3: require('./images/pic_xs_tx.png'),
    yesCircle: require('./images/ic_yuan_gou.png'),
    noCircle: require('./images/ic_yuan_cha.png'),
    clockBlue: require('./images/clock_blue.png'),
    notice: require('./images/ic_xinxi.png'),
    medal: require('./images/ic_xunzhang.png'),
    calendar: require('./images/ic_rl.png'),
    arrowRight: require('./images/ic_right.png'),
    arrowLeft: require('./images/ic_left.png'),
    arrowDown: require('./images/ic_dnow.png'),
    modalClose: require('./images/ic_del.png'),
    loginPeople: require('./images/login_people.png'),
    loginLock: require('./images/login_lock.png'),
    logo: require('./images/ic_logo.png'),
    peopleMore: require('./images/ic_tj.png'),
    yesWhite: require('./images/ic_gou_w.png'),
    noWhite: require('./images/ic_cha_w.png'),
    peopleGroupWhite: require('./images/ic_rs_w.png'),
    teacherBg: require('./images/bg_jy.png'),
    ratingBg: require('./images/bg_jy_dnow.png'),
    yesCircleRed: require('./images/ic_gou_r.png'),
    noCircleRed: require('./images/ic_yuan_cha.png'),
    starGreen: require('./images/ic_xin_g.png'),
    starRed: require('./images/ic_xin_r.png'),
    starGrey: require('./images/ic_xin_h.png'),
    search: require('./images/ic_shou.png'),
    delete: require('./images/ic_ss_del.png'),
    arrowLeftGrey: require('./images/ic_right_h.png'),
    
}

export default images
