

 module.exports = {

    //local storage 

    USER:'USER',

    ORDER_SERVICE_WAITING : 'WAITING',
    ORDER_SERVICE_NEW_ORDER : 'NEWORDER',
    ORDER_SERVICE_ACCEPTED : 'ACCEPTED',
    ORDER_SERVICE_ACCEPTED_CONFIRMED : 'ACCEPTED_CONFIRMED',
    ORDER_SERVICE_REJECTED : 'REJECTED',
    ORDER_SERVICE_SERVING : 'SERVING',
    ORDER_SERVICE_ARRIVED : 'ARRIVED',
    ORDER_SERVICE_FINISHED : 'FINISHED'

    
 }