export const STColor = {
    MAIN_GREEN:'#799D3B',
    UNDER_LINE_COLOR: "#BEBEBE",
    FONT_TITLE_COLOR:"#333333",
    FONT_LABEL_COLOR:'#999999',
    LINE_COLOR:"#EFEFEF",
    LINE_ITEM_COLOR:"#E7E7E7",
    AVATAR_BODER_COLOR:'#979797',
    PHONE_UNDERLINE_COLOR:"#799D3B",
    DOT_GREEN_COLOR:"#6E9137",
    DOT_ORANGE_COLOR:"#FFA42B",
    FONT_GREEN_COLOR:"#6E9137",
    ICON_BG_COLOR:'#F6F6F6',
    NUM_COLOR:"#7A9E3C",
    MAIN_ORANGE:'#FFA42B',
    INPUT_LINE_COLOR:"#CFCFCF",
    INPUT_PLEACEHOLDER_COLOR:'#BEBEBE'

}
